name: Update Tech News Section

on:
  schedule:
    - cron: '0 */8 * * *'  # A cada 8 horas
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  update-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install Dependencies
      run: pip install requests
      
    - name: Update News Section
      env:
        NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
      working-directory: ./scripts
      run: python generate_apis_news.py
      
    - name: Commit News Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action - News"
        git add README.md
        git diff --quiet && git diff --staged --quiet || git commit -m "ðŸ“° Update tech news section"
        git push